drop table if exists USER_TABLE CASCADE;
create table USER_TABLE
(
    id bigint generated by default as identity,
    name varchar(255),
    email varchar(255),
    createdAt date,
    updatedAt date,
    primary key (id)
);
insert into USER_TABLE(id, name, email, createdAt, updatedAt) values (1, 'test', 'test@email.com', now(), now());
insert into USER_TABLE(id, name, email, createdAt, updatedAt) values (2, 'test2', 'test2@email.com', now(), now());
insert into USER_TABLE(id, name, email, createdAt, updatedAt) values (3, 'test3', 'test3@email.com', now(), now());